In [99]:
import PIL
from PIL import Image
import requests
from io import BytesIO
import numpy as np 

a = [[[1,1,1,1],
      [2,2,2,2]],
      [[3,3,3,3],
      [4,4,4,4]],
      [[5,5,5,5],
      [6,6,6,6]]]

a = np.asarray(a)

print (a.shape)
print (a.ravel())
b = np.rollaxis(a, 2)
print (b.shape)
print (b.ravel())
c = a
print (c[:,:,1:4])
c[:,:,1:4] = 0
print (c)
c = np.rollaxis(c, 2)
c = c.ravel()
print (c)
c = c.reshape(4,3,2)
print (c.shape)
c = np.rollaxis(c, 2)
c = np.rollaxis(c, 2)
print (c.ravel()[0:5])


(3, 2, 4)
[1 1 1 1 2 2 2 2 3 3 3 3 4 4 4 4 5 5 5 5 6 6 6 6]
(4, 3, 2)
[1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6 1 2 3 4 5 6]
[[[1 1 1]
  [2 2 2]]

 [[3 3 3]
  [4 4 4]]

 [[5 5 5]
  [6 6 6]]]
[[[1 0 0 0]
  [2 0 0 0]]

 [[3 0 0 0]
  [4 0 0 0]]

 [[5 0 0 0]
  [6 0 0 0]]]
[1 2 3 4 5 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
(4, 3, 2)
[1 0 0 0 2]
